services:
  strapi:
    image: ghcr.io/vlad-vishnevskii/strapi-tili-mili:latest
    container_name: strapi-tili-mili
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      IS_PROXIED: "true"
    ports:
      - "1337:1337"
    volumes:
      - ./data/sqlite:/app/.tmp
      - ./data/uploads:/app/public/uploads
